

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class BancosCorretores : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the BancosCorretores entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BancosCorretores()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BancosCorretores(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BancosCorretores> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.BancosCorretores.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BancosCorretores_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BancosCorretores_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.BancosCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Agencia
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Agencia);
            }
            set
            {
                global::LightSwitchApplication.BancosCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Agencia, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Agencia_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Agencia_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Agencia_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Conta
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Conta);
            }
            set
            {
                global::LightSwitchApplication.BancosCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Conta, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Conta_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Conta_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Conta_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.BancosCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Corretores Corretores
        {
            get
            {
                return global::LightSwitchApplication.BancosCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Corretores);
            }
            set
            {
                global::LightSwitchApplication.BancosCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Corretores, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Corretores_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Corretores_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Corretores_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.BancosCorretores,
                global::LightSwitchApplication.BancosCorretores.DetailsClass,
                global::LightSwitchApplication.BancosCorretores.DetailsClass.IImplementation,
                global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass>.Entry
                __BancosCorretoresEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass>.Entry(
                    global::LightSwitchApplication.BancosCorretores.DetailsClass.__BancosCorretores_CreateNew,
                    global::LightSwitchApplication.BancosCorretores.DetailsClass.__BancosCorretores_Created,
                    global::LightSwitchApplication.BancosCorretores.DetailsClass.__BancosCorretores_AllowSaveWithErrors);
            private static global::LightSwitchApplication.BancosCorretores __BancosCorretores_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BancosCorretores> es)
            {
                return new global::LightSwitchApplication.BancosCorretores(es);
            }
            private static void __BancosCorretores_Created(global::LightSwitchApplication.BancosCorretores e)
            {
                e.BancosCorretores_Created();
            }
            private static bool __BancosCorretores_AllowSaveWithErrors(global::LightSwitchApplication.BancosCorretores e)
            {
                bool result = false;
                e.BancosCorretores_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string> Agencia
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Agencia) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string> Conta
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Conta) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::LightSwitchApplication.Corretores> Corretores
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Corretores) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::LightSwitchApplication.Corretores>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Agencia { get; set; }
                new string Conta { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Corretores { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, int>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry
                    Agencia = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry(
                        "Agencia",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Agencia_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Agencia_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Agencia_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Agencia_GetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Agencia_SetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Agencia_OnValueChanged);
                private static void _Agencia_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Agencia, sf);
                }
                private static bool _Agencia_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.Agencia_IsReadOnly(ref result);
                    return result;
                }
                private static void _Agencia_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Agencia_Validate(r);
                }
                private static string _Agencia_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Agencia;
                }
                private static void _Agencia_SetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Agencia = v;
                }
                private static void _Agencia_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.Agencia_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry
                    Conta = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry(
                        "Conta",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Conta_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Conta_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Conta_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Conta_GetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Conta_SetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Conta_OnValueChanged);
                private static void _Conta_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Conta, sf);
                }
                private static bool _Conta_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.Conta_IsReadOnly(ref result);
                    return result;
                }
                private static void _Conta_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Conta_Validate(r);
                }
                private static string _Conta_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Conta;
                }
                private static void _Conta_SetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Conta = v;
                }
                private static void _Conta_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.Conta_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Entry
                    Corretores = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Entry(
                        "Corretores",
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_Stub,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_ComputeIsReadOnly,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_Validate,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_GetCoreImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_GetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_SetImplementationValue,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_Refresh,
                        global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties._Corretores_OnValueChanged);
                private static void _Corretores_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BancosCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Data> c, global::LightSwitchApplication.BancosCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Corretores, sf);
                }
                private static bool _Corretores_ComputeIsReadOnly(global::LightSwitchApplication.BancosCorretores e)
                {
                    bool result = false;
                    e.Corretores_IsReadOnly(ref result);
                    return result;
                }
                private static void _Corretores_Validate(global::LightSwitchApplication.BancosCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Corretores_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Corretores_GetCoreImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Corretores;
                }
                private static global::LightSwitchApplication.Corretores _Corretores_GetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Corretores, global::LightSwitchApplication.Corretores.DetailsClass>(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Corretores, ref d._Corretores);
                }
                private static void _Corretores_SetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass d, global::LightSwitchApplication.Corretores v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Corretores, ref d._Corretores, (i, ev) => i.Corretores = ev, v);
                }
                private static void _Corretores_Refresh(global::LightSwitchApplication.BancosCorretores.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.BancosCorretores.DetailsClass.PropertySetProperties.Corretores, ref d._Corretores);
                }
                private static void _Corretores_OnValueChanged(global::LightSwitchApplication.BancosCorretores e)
                {
                    e.Corretores_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data _Agencia;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data _Conta;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.BancosCorretores, global::LightSwitchApplication.BancosCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Data _Corretores;
            
        }
    
        #endregion
    }
    
    #endregion
}
