

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class EnderecoSegurado : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EnderecoSegurado entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EnderecoSegurado()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EnderecoSegurado(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EnderecoSegurado> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EnderecoSegurado.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EnderecoSegurado_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EnderecoSegurado_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Rua
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Rua);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Rua, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rua_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rua_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rua_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Bairro
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Bairro);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Bairro, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bairro_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bairro_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bairro_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Numero
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Numero);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Numero, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Numero_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Numero_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Numero_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Complemento
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Complemento);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Complemento, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Complemento_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Complemento_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Complemento_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Cidade
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Cidade);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Cidade, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cidade_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cidade_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cidade_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UF
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.UF);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.UF, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UF_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UF_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UF_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CEP
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.CEP);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.CEP, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CEP_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CEP_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CEP_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Fiscal
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Fiscal);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Fiscal, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fiscal_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fiscal_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fiscal_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Segurados Segurados
        {
            get
            {
                return global::LightSwitchApplication.EnderecoSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Segurados);
            }
            set
            {
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Segurados, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Segurados_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Segurados_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Segurados_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EnderecoSegurado,
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass,
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.IImplementation,
                global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass>.Entry
                __EnderecoSeguradoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass>.Entry(
                    global::LightSwitchApplication.EnderecoSegurado.DetailsClass.__EnderecoSegurado_CreateNew,
                    global::LightSwitchApplication.EnderecoSegurado.DetailsClass.__EnderecoSegurado_Created,
                    global::LightSwitchApplication.EnderecoSegurado.DetailsClass.__EnderecoSegurado_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EnderecoSegurado __EnderecoSegurado_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EnderecoSegurado> es)
            {
                return new global::LightSwitchApplication.EnderecoSegurado(es);
            }
            private static void __EnderecoSegurado_Created(global::LightSwitchApplication.EnderecoSegurado e)
            {
                e.EnderecoSegurado_Created();
            }
            private static bool __EnderecoSegurado_AllowSaveWithErrors(global::LightSwitchApplication.EnderecoSegurado e)
            {
                bool result = false;
                e.EnderecoSegurado_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> Rua
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Rua) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> Bairro
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Bairro) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<int>> Numero
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Numero) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> Complemento
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Complemento) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> Cidade
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Cidade) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> UF
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.UF) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> CEP
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.CEP) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<bool>> Fiscal
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Fiscal) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::LightSwitchApplication.Segurados> Segurados
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Segurados) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::LightSwitchApplication.Segurados>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Rua { get; set; }
                new string Bairro { get; set; }
                new global::System.Nullable<int> Numero { get; set; }
                new string Complemento { get; set; }
                new string Cidade { get; set; }
                new string UF { get; set; }
                new string CEP { get; set; }
                new global::System.Nullable<bool> Fiscal { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Segurados { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, int>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    Rua = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "Rua",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Rua_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Rua_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Rua_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Rua_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Rua_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Rua_OnValueChanged);
                private static void _Rua_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Rua, sf);
                }
                private static bool _Rua_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Rua_IsReadOnly(ref result);
                    return result;
                }
                private static void _Rua_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Rua_Validate(r);
                }
                private static string _Rua_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Rua;
                }
                private static void _Rua_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Rua = v;
                }
                private static void _Rua_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Rua_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    Bairro = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "Bairro",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Bairro_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Bairro_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Bairro_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Bairro_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Bairro_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Bairro_OnValueChanged);
                private static void _Bairro_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Bairro, sf);
                }
                private static bool _Bairro_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Bairro_IsReadOnly(ref result);
                    return result;
                }
                private static void _Bairro_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Bairro_Validate(r);
                }
                private static string _Bairro_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Bairro;
                }
                private static void _Bairro_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Bairro = v;
                }
                private static void _Bairro_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Bairro_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<int>>.Entry
                    Numero = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Numero",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Numero_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Numero_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Numero_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Numero_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Numero_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Numero_OnValueChanged);
                private static void _Numero_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Numero, sf);
                }
                private static bool _Numero_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Numero_IsReadOnly(ref result);
                    return result;
                }
                private static void _Numero_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Numero_Validate(r);
                }
                private static global::System.Nullable<int> _Numero_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Numero;
                }
                private static void _Numero_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Numero = v;
                }
                private static void _Numero_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Numero_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    Complemento = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "Complemento",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Complemento_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Complemento_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Complemento_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Complemento_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Complemento_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Complemento_OnValueChanged);
                private static void _Complemento_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Complemento, sf);
                }
                private static bool _Complemento_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Complemento_IsReadOnly(ref result);
                    return result;
                }
                private static void _Complemento_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Complemento_Validate(r);
                }
                private static string _Complemento_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Complemento;
                }
                private static void _Complemento_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Complemento = v;
                }
                private static void _Complemento_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Complemento_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    Cidade = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "Cidade",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Cidade_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Cidade_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Cidade_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Cidade_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Cidade_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Cidade_OnValueChanged);
                private static void _Cidade_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Cidade, sf);
                }
                private static bool _Cidade_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Cidade_IsReadOnly(ref result);
                    return result;
                }
                private static void _Cidade_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Cidade_Validate(r);
                }
                private static string _Cidade_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Cidade;
                }
                private static void _Cidade_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Cidade = v;
                }
                private static void _Cidade_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Cidade_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    UF = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "UF",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._UF_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._UF_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._UF_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._UF_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._UF_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._UF_OnValueChanged);
                private static void _UF_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._UF, sf);
                }
                private static bool _UF_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.UF_IsReadOnly(ref result);
                    return result;
                }
                private static void _UF_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UF_Validate(r);
                }
                private static string _UF_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.UF;
                }
                private static void _UF_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UF = v;
                }
                private static void _UF_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.UF_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    CEP = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "CEP",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CEP_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CEP_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CEP_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CEP_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CEP_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CEP_OnValueChanged);
                private static void _CEP_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._CEP, sf);
                }
                private static bool _CEP_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.CEP_IsReadOnly(ref result);
                    return result;
                }
                private static void _CEP_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CEP_Validate(r);
                }
                private static string _CEP_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.CEP;
                }
                private static void _CEP_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CEP = v;
                }
                private static void _CEP_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.CEP_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<bool>>.Entry
                    Fiscal = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Fiscal",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Fiscal_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Fiscal_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Fiscal_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Fiscal_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Fiscal_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Fiscal_OnValueChanged);
                private static void _Fiscal_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Fiscal, sf);
                }
                private static bool _Fiscal_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Fiscal_IsReadOnly(ref result);
                    return result;
                }
                private static void _Fiscal_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Fiscal_Validate(r);
                }
                private static global::System.Nullable<bool> _Fiscal_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Fiscal;
                }
                private static void _Fiscal_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Fiscal = v;
                }
                private static void _Fiscal_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Fiscal_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Entry
                    Segurados = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Entry(
                        "Segurados",
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_Stub,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_Validate,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_GetCoreImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_GetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_SetImplementationValue,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_Refresh,
                        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties._Segurados_OnValueChanged);
                private static void _Segurados_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Data> c, global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Segurados, sf);
                }
                private static bool _Segurados_ComputeIsReadOnly(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    bool result = false;
                    e.Segurados_IsReadOnly(ref result);
                    return result;
                }
                private static void _Segurados_Validate(global::LightSwitchApplication.EnderecoSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Segurados_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Segurados_GetCoreImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Segurados;
                }
                private static global::LightSwitchApplication.Segurados _Segurados_GetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Segurados, global::LightSwitchApplication.Segurados.DetailsClass>(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Segurados, ref d._Segurados);
                }
                private static void _Segurados_SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d, global::LightSwitchApplication.Segurados v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Segurados, ref d._Segurados, (i, ev) => i.Segurados = ev, v);
                }
                private static void _Segurados_Refresh(global::LightSwitchApplication.EnderecoSegurado.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EnderecoSegurado.DetailsClass.PropertySetProperties.Segurados, ref d._Segurados);
                }
                private static void _Segurados_OnValueChanged(global::LightSwitchApplication.EnderecoSegurado e)
                {
                    e.Segurados_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _Rua;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _Bairro;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<int>>.Data _Numero;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _Complemento;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _Cidade;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _UF;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _CEP;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<bool>>.Data _Fiscal;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EnderecoSegurado, global::LightSwitchApplication.EnderecoSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Data _Segurados;
            
        }
    
        #endregion
    }
    
    #endregion
}
