//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Segurados
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Segurados :
        global::LightSwitchApplication.Segurados.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnSeguradoChanged()
        {
            this.___OnPropertyChanged("Segurado");
        }
        
        partial void OnFisicaChanged()
        {
            this.___OnPropertyChanged("Fisica");
        }
        
        partial void OnJuridicaChanged()
        {
            this.___OnPropertyChanged("Juridica");
        }
        
        partial void OnCpfCnpjChanged()
        {
            this.___OnPropertyChanged("CpfCnpj");
        }
        
        partial void OnRgChanged()
        {
            this.___OnPropertyChanged("Rg");
        }
        
        partial void OnDataExpedicaoChanged()
        {
            this.___OnPropertyChanged("DataExpedicao");
        }
        
        partial void OnOrgaoExpedicaoChanged()
        {
            this.___OnPropertyChanged("OrgaoExpedicao");
        }
        
        partial void OnDataNascimentoChanged()
        {
            this.___OnPropertyChanged("DataNascimento");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Segurados.DetailsClass.IImplementation.CelularSeguradoes
        {
            get
            {
                return this.CelularSeguradoes;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CelularSegurado> __CelularSeguradoes
        {
            get
            {
                if (this.___CelularSeguradoes == null)
                {
                    this.___CelularSeguradoes = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CelularSegurado>(
                        this,
                        "CelularSeguradoes",
                        () => this._CelularSeguradoes,
                        e => global::System.Object.Equals(e.CelularSegurado_Segurados, this.Id));
                }
                return this.___CelularSeguradoes;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CelularSegurado> ___CelularSeguradoes;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Segurados.DetailsClass.IImplementation.EmailSeguradoes
        {
            get
            {
                return this.EmailSeguradoes;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmailSegurado> __EmailSeguradoes
        {
            get
            {
                if (this.___EmailSeguradoes == null)
                {
                    this.___EmailSeguradoes = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmailSegurado>(
                        this,
                        "EmailSeguradoes",
                        () => this._EmailSeguradoes,
                        e => global::System.Object.Equals(e.EmailSegurado_Segurados1, this.Id));
                }
                return this.___EmailSeguradoes;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmailSegurado> ___EmailSeguradoes;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Segurados.DetailsClass.IImplementation.EnderecoSeguradoes
        {
            get
            {
                return this.EnderecoSeguradoes;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EnderecoSegurado> __EnderecoSeguradoes
        {
            get
            {
                if (this.___EnderecoSeguradoes == null)
                {
                    this.___EnderecoSeguradoes = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EnderecoSegurado>(
                        this,
                        "EnderecoSeguradoes",
                        () => this._EnderecoSeguradoes,
                        e => global::System.Object.Equals(e.EnderecoSegurado_Segurados, this.Id));
                }
                return this.___EnderecoSeguradoes;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EnderecoSegurado> ___EnderecoSeguradoes;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Segurados.DetailsClass.IImplementation.TelefonesSeguradoes
        {
            get
            {
                return this.TelefonesSeguradoes;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TelefonesSegurado> __TelefonesSeguradoes
        {
            get
            {
                if (this.___TelefonesSeguradoes == null)
                {
                    this.___TelefonesSeguradoes = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TelefonesSegurado>(
                        this,
                        "TelefonesSeguradoes",
                        () => this._TelefonesSeguradoes,
                        e => global::System.Object.Equals(e.TelefonesSegurado_Segurados1, this.Id));
                }
                return this.___TelefonesSeguradoes;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TelefonesSegurado> ___TelefonesSeguradoes;
        
    }
    #endregion
    
    #region EnderecoSegurado
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EnderecoSegurado :
        global::LightSwitchApplication.EnderecoSegurado.DetailsClass.IImplementation
    {
        partial void OnEnderecoSegurado_SeguradosChanged()
        {
            this.___OnPropertyChanged("EnderecoSegurado_Segurados");
            this.___OnPropertyChanged("Segurados");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRuaChanged()
        {
            this.___OnPropertyChanged("Rua");
        }
        
        partial void OnBairroChanged()
        {
            this.___OnPropertyChanged("Bairro");
        }
        
        partial void OnNumeroChanged()
        {
            this.___OnPropertyChanged("Numero");
        }
        
        partial void OnComplementoChanged()
        {
            this.___OnPropertyChanged("Complemento");
        }
        
        partial void OnCidadeChanged()
        {
            this.___OnPropertyChanged("Cidade");
        }
        
        partial void OnUFChanged()
        {
            this.___OnPropertyChanged("UF");
        }
        
        partial void OnCEPChanged()
        {
            this.___OnPropertyChanged("CEP");
        }
        
        partial void OnFiscalChanged()
        {
            this.___OnPropertyChanged("Fiscal");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EnderecoSegurado.DetailsClass.IImplementation.Segurados
        {
            get
            {
                return this.Segurados;
            }
            set
            {
                this.Segurados = (global::LightSwitchApplication.Implementation.Segurados)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> __Segurados
        {
            get
            {
                if (this.___Segurados == null)
                {
                    this.___Segurados = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados>(
                        this,
                        "Segurados",
                        new string[] { "EnderecoSegurado_Segurados" },
                        e => global::System.Object.Equals(e.Id, this.EnderecoSegurado_Segurados),
                        () => this._Segurados,
                        e => this._Segurados = e);
                }
                return this.___Segurados;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> ___Segurados;
        
    }
    #endregion
    
    #region EmailSegurado
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmailSegurado :
        global::LightSwitchApplication.EmailSegurado.DetailsClass.IImplementation
    {
        partial void OnEmailSegurado_Segurados1Changed()
        {
            this.___OnPropertyChanged("EmailSegurado_Segurados1");
            this.___OnPropertyChanged("Segurados");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnemailChanged()
        {
            this.___OnPropertyChanged("email");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmailSegurado.DetailsClass.IImplementation.Segurados
        {
            get
            {
                return this.Segurados;
            }
            set
            {
                this.Segurados = (global::LightSwitchApplication.Implementation.Segurados)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> __Segurados
        {
            get
            {
                if (this.___Segurados == null)
                {
                    this.___Segurados = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados>(
                        this,
                        "Segurados",
                        new string[] { "EmailSegurado_Segurados1" },
                        e => global::System.Object.Equals(e.Id, this.EmailSegurado_Segurados1),
                        () => this._Segurados,
                        e => this._Segurados = e);
                }
                return this.___Segurados;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> ___Segurados;
        
    }
    #endregion
    
    #region TelefonesSegurado
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TelefonesSegurado :
        global::LightSwitchApplication.TelefonesSegurado.DetailsClass.IImplementation
    {
        partial void OnTelefonesSegurado_Segurados1Changed()
        {
            this.___OnPropertyChanged("TelefonesSegurado_Segurados1");
            this.___OnPropertyChanged("Segurados");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnTelefoneChanged()
        {
            this.___OnPropertyChanged("Telefone");
        }
        
        partial void OnComercialChanged()
        {
            this.___OnPropertyChanged("Comercial");
        }
        
        partial void OnRecadosChanged()
        {
            this.___OnPropertyChanged("Recados");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TelefonesSegurado.DetailsClass.IImplementation.Segurados
        {
            get
            {
                return this.Segurados;
            }
            set
            {
                this.Segurados = (global::LightSwitchApplication.Implementation.Segurados)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> __Segurados
        {
            get
            {
                if (this.___Segurados == null)
                {
                    this.___Segurados = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados>(
                        this,
                        "Segurados",
                        new string[] { "TelefonesSegurado_Segurados1" },
                        e => global::System.Object.Equals(e.Id, this.TelefonesSegurado_Segurados1),
                        () => this._Segurados,
                        e => this._Segurados = e);
                }
                return this.___Segurados;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> ___Segurados;
        
    }
    #endregion
    
    #region CelularSegurado
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CelularSegurado :
        global::LightSwitchApplication.CelularSegurado.DetailsClass.IImplementation
    {
        partial void OnCelularSegurado_SeguradosChanged()
        {
            this.___OnPropertyChanged("CelularSegurado_Segurados");
            this.___OnPropertyChanged("Segurados");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCelularChanged()
        {
            this.___OnPropertyChanged("Celular");
        }
        
        partial void OnComercialChanged()
        {
            this.___OnPropertyChanged("Comercial");
        }
        
        partial void OnRecadosChanged()
        {
            this.___OnPropertyChanged("Recados");
        }
        
        partial void OnNextelChanged()
        {
            this.___OnPropertyChanged("Nextel");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CelularSegurado.DetailsClass.IImplementation.Segurados
        {
            get
            {
                return this.Segurados;
            }
            set
            {
                this.Segurados = (global::LightSwitchApplication.Implementation.Segurados)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> __Segurados
        {
            get
            {
                if (this.___Segurados == null)
                {
                    this.___Segurados = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados>(
                        this,
                        "Segurados",
                        new string[] { "CelularSegurado_Segurados" },
                        e => global::System.Object.Equals(e.Id, this.CelularSegurado_Segurados),
                        () => this._Segurados,
                        e => this._Segurados = e);
                }
                return this.___Segurados;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Segurados> ___Segurados;
        
    }
    #endregion
    
    #region Corretores
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Corretores :
        global::LightSwitchApplication.Corretores.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCorretorChanged()
        {
            this.___OnPropertyChanged("Corretor");
        }
        
        partial void OnDataNascimentoChanged()
        {
            this.___OnPropertyChanged("DataNascimento");
        }
        
        partial void OnRgChanged()
        {
            this.___OnPropertyChanged("Rg");
        }
        
        partial void OnDataExpedicaoChanged()
        {
            this.___OnPropertyChanged("DataExpedicao");
        }
        
        partial void OnOrgaoExpedicaoChanged()
        {
            this.___OnPropertyChanged("OrgaoExpedicao");
        }
        
        partial void OnCpfCnpjChanged()
        {
            this.___OnPropertyChanged("CpfCnpj");
        }
        
        partial void OnSusepChanged()
        {
            this.___OnPropertyChanged("Susep");
        }
        
        partial void OnCodChubChanged()
        {
            this.___OnPropertyChanged("CodChub");
        }
        
        partial void OnLoginPortalChanged()
        {
            this.___OnPropertyChanged("LoginPortal");
        }
        
        partial void OnSenhaPortalChanged()
        {
            this.___OnPropertyChanged("SenhaPortal");
        }
        
        partial void OnLoginExtranetChanged()
        {
            this.___OnPropertyChanged("LoginExtranet");
        }
        
        partial void OnSenhaExtranetChanged()
        {
            this.___OnPropertyChanged("SenhaExtranet");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Corretores.DetailsClass.IImplementation.BancosCorretoresCollection
        {
            get
            {
                return this.BancosCorretoresCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.BancosCorretores> __BancosCorretoresCollection
        {
            get
            {
                if (this.___BancosCorretoresCollection == null)
                {
                    this.___BancosCorretoresCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.BancosCorretores>(
                        this,
                        "BancosCorretoresCollection",
                        () => this._BancosCorretoresCollection,
                        e => global::System.Object.Equals(e.BancosCorretores_Corretores, this.Id));
                }
                return this.___BancosCorretoresCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.BancosCorretores> ___BancosCorretoresCollection;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Corretores.DetailsClass.IImplementation.CelularCorretoresCollection
        {
            get
            {
                return this.CelularCorretoresCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CelularCorretores> __CelularCorretoresCollection
        {
            get
            {
                if (this.___CelularCorretoresCollection == null)
                {
                    this.___CelularCorretoresCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CelularCorretores>(
                        this,
                        "CelularCorretoresCollection",
                        () => this._CelularCorretoresCollection,
                        e => global::System.Object.Equals(e.CelularCorretores_Corretores, this.Id));
                }
                return this.___CelularCorretoresCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CelularCorretores> ___CelularCorretoresCollection;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Corretores.DetailsClass.IImplementation.EmailCorretoresCollection
        {
            get
            {
                return this.EmailCorretoresCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmailCorretores> __EmailCorretoresCollection
        {
            get
            {
                if (this.___EmailCorretoresCollection == null)
                {
                    this.___EmailCorretoresCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmailCorretores>(
                        this,
                        "EmailCorretoresCollection",
                        () => this._EmailCorretoresCollection,
                        e => global::System.Object.Equals(e.EmailCorretores_Corretores, this.Id));
                }
                return this.___EmailCorretoresCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmailCorretores> ___EmailCorretoresCollection;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Corretores.DetailsClass.IImplementation.EnderecoCorretoresCollection
        {
            get
            {
                return this.EnderecoCorretoresCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EnderecoCorretores> __EnderecoCorretoresCollection
        {
            get
            {
                if (this.___EnderecoCorretoresCollection == null)
                {
                    this.___EnderecoCorretoresCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EnderecoCorretores>(
                        this,
                        "EnderecoCorretoresCollection",
                        () => this._EnderecoCorretoresCollection,
                        e => global::System.Object.Equals(e.EnderecoCorretores_Corretores, this.Id));
                }
                return this.___EnderecoCorretoresCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EnderecoCorretores> ___EnderecoCorretoresCollection;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Corretores.DetailsClass.IImplementation.TelefonesCorretoresCollection
        {
            get
            {
                return this.TelefonesCorretoresCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TelefonesCorretores> __TelefonesCorretoresCollection
        {
            get
            {
                if (this.___TelefonesCorretoresCollection == null)
                {
                    this.___TelefonesCorretoresCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TelefonesCorretores>(
                        this,
                        "TelefonesCorretoresCollection",
                        () => this._TelefonesCorretoresCollection,
                        e => global::System.Object.Equals(e.TelefonesCorretores_Corretores, this.Id));
                }
                return this.___TelefonesCorretoresCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TelefonesCorretores> ___TelefonesCorretoresCollection;
        
    }
    #endregion
    
    #region EnderecoCorretores
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EnderecoCorretores :
        global::LightSwitchApplication.EnderecoCorretores.DetailsClass.IImplementation
    {
        partial void OnEnderecoCorretores_CorretoresChanged()
        {
            this.___OnPropertyChanged("EnderecoCorretores_Corretores");
            this.___OnPropertyChanged("Corretores");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRuaChanged()
        {
            this.___OnPropertyChanged("Rua");
        }
        
        partial void OnBairroChanged()
        {
            this.___OnPropertyChanged("Bairro");
        }
        
        partial void OnNumeroChanged()
        {
            this.___OnPropertyChanged("Numero");
        }
        
        partial void OnComplementoChanged()
        {
            this.___OnPropertyChanged("Complemento");
        }
        
        partial void OnCidadeChanged()
        {
            this.___OnPropertyChanged("Cidade");
        }
        
        partial void OnUFChanged()
        {
            this.___OnPropertyChanged("UF");
        }
        
        partial void OnCEPChanged()
        {
            this.___OnPropertyChanged("CEP");
        }
        
        partial void OnFiscalChanged()
        {
            this.___OnPropertyChanged("Fiscal");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EnderecoCorretores.DetailsClass.IImplementation.Corretores
        {
            get
            {
                return this.Corretores;
            }
            set
            {
                this.Corretores = (global::LightSwitchApplication.Implementation.Corretores)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> __Corretores
        {
            get
            {
                if (this.___Corretores == null)
                {
                    this.___Corretores = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores>(
                        this,
                        "Corretores",
                        new string[] { "EnderecoCorretores_Corretores" },
                        e => global::System.Object.Equals(e.Id, this.EnderecoCorretores_Corretores),
                        () => this._Corretores,
                        e => this._Corretores = e);
                }
                return this.___Corretores;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> ___Corretores;
        
    }
    #endregion
    
    #region TelefonesCorretores
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TelefonesCorretores :
        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.IImplementation
    {
        partial void OnTelefonesCorretores_CorretoresChanged()
        {
            this.___OnPropertyChanged("TelefonesCorretores_Corretores");
            this.___OnPropertyChanged("Corretores");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnTelefoneChanged()
        {
            this.___OnPropertyChanged("Telefone");
        }
        
        partial void OnComercialChanged()
        {
            this.___OnPropertyChanged("Comercial");
        }
        
        partial void OnRecadosChanged()
        {
            this.___OnPropertyChanged("Recados");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TelefonesCorretores.DetailsClass.IImplementation.Corretores
        {
            get
            {
                return this.Corretores;
            }
            set
            {
                this.Corretores = (global::LightSwitchApplication.Implementation.Corretores)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> __Corretores
        {
            get
            {
                if (this.___Corretores == null)
                {
                    this.___Corretores = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores>(
                        this,
                        "Corretores",
                        new string[] { "TelefonesCorretores_Corretores" },
                        e => global::System.Object.Equals(e.Id, this.TelefonesCorretores_Corretores),
                        () => this._Corretores,
                        e => this._Corretores = e);
                }
                return this.___Corretores;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> ___Corretores;
        
    }
    #endregion
    
    #region EmailCorretores
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmailCorretores :
        global::LightSwitchApplication.EmailCorretores.DetailsClass.IImplementation
    {
        partial void OnEmailCorretores_CorretoresChanged()
        {
            this.___OnPropertyChanged("EmailCorretores_Corretores");
            this.___OnPropertyChanged("Corretores");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnemailChanged()
        {
            this.___OnPropertyChanged("email");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmailCorretores.DetailsClass.IImplementation.Corretores
        {
            get
            {
                return this.Corretores;
            }
            set
            {
                this.Corretores = (global::LightSwitchApplication.Implementation.Corretores)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> __Corretores
        {
            get
            {
                if (this.___Corretores == null)
                {
                    this.___Corretores = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores>(
                        this,
                        "Corretores",
                        new string[] { "EmailCorretores_Corretores" },
                        e => global::System.Object.Equals(e.Id, this.EmailCorretores_Corretores),
                        () => this._Corretores,
                        e => this._Corretores = e);
                }
                return this.___Corretores;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> ___Corretores;
        
    }
    #endregion
    
    #region CelularCorretores
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CelularCorretores :
        global::LightSwitchApplication.CelularCorretores.DetailsClass.IImplementation
    {
        partial void OnCelularCorretores_CorretoresChanged()
        {
            this.___OnPropertyChanged("CelularCorretores_Corretores");
            this.___OnPropertyChanged("Corretores");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCelularChanged()
        {
            this.___OnPropertyChanged("Celular");
        }
        
        partial void OnComercialChanged()
        {
            this.___OnPropertyChanged("Comercial");
        }
        
        partial void OnRecadosChanged()
        {
            this.___OnPropertyChanged("Recados");
        }
        
        partial void OnNextelChanged()
        {
            this.___OnPropertyChanged("Nextel");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CelularCorretores.DetailsClass.IImplementation.Corretores
        {
            get
            {
                return this.Corretores;
            }
            set
            {
                this.Corretores = (global::LightSwitchApplication.Implementation.Corretores)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> __Corretores
        {
            get
            {
                if (this.___Corretores == null)
                {
                    this.___Corretores = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores>(
                        this,
                        "Corretores",
                        new string[] { "CelularCorretores_Corretores" },
                        e => global::System.Object.Equals(e.Id, this.CelularCorretores_Corretores),
                        () => this._Corretores,
                        e => this._Corretores = e);
                }
                return this.___Corretores;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> ___Corretores;
        
    }
    #endregion
    
    #region BancosCorretores
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class BancosCorretores :
        global::LightSwitchApplication.BancosCorretores.DetailsClass.IImplementation
    {
        partial void OnBancosCorretores_CorretoresChanged()
        {
            this.___OnPropertyChanged("BancosCorretores_Corretores");
            this.___OnPropertyChanged("Corretores");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnAgenciaChanged()
        {
            this.___OnPropertyChanged("Agencia");
        }
        
        partial void OnContaChanged()
        {
            this.___OnPropertyChanged("Conta");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BancosCorretores.DetailsClass.IImplementation.Corretores
        {
            get
            {
                return this.Corretores;
            }
            set
            {
                this.Corretores = (global::LightSwitchApplication.Implementation.Corretores)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> __Corretores
        {
            get
            {
                if (this.___Corretores == null)
                {
                    this.___Corretores = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores>(
                        this,
                        "Corretores",
                        new string[] { "BancosCorretores_Corretores" },
                        e => global::System.Object.Equals(e.Id, this.BancosCorretores_Corretores),
                        () => this._Corretores,
                        e => this._Corretores = e);
                }
                return this.___Corretores;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Corretores> ___Corretores;
        
    }
    #endregion
    
    #region Ramos
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Ramos :
        global::LightSwitchApplication.Ramos.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNomeChanged()
        {
            this.___OnPropertyChanged("Nome");
        }
        
        partial void OnDescricaoChanged()
        {
            this.___OnPropertyChanged("Descricao");
        }
        
        partial void OnComissaoChanged()
        {
            this.___OnPropertyChanged("Comissao");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
    }
    #endregion
    
    #region PropostasHeader
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PropostasHeader :
        global::LightSwitchApplication.PropostasHeader.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNumeroPropostaChanged()
        {
            this.___OnPropertyChanged("NumeroProposta");
        }
        
        partial void OnInicioVigenciaChanged()
        {
            this.___OnPropertyChanged("InicioVigencia");
        }
        
        partial void OnFimViegnciaChanged()
        {
            this.___OnPropertyChanged("FimViegncia");
        }
        
        partial void OnDataCotacaoChanged()
        {
            this.___OnPropertyChanged("DataCotacao");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Segurados))
            {
                return new global::LightSwitchApplication.Implementation.Segurados();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EnderecoSegurado))
            {
                return new global::LightSwitchApplication.Implementation.EnderecoSegurado();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmailSegurado))
            {
                return new global::LightSwitchApplication.Implementation.EmailSegurado();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TelefonesSegurado))
            {
                return new global::LightSwitchApplication.Implementation.TelefonesSegurado();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CelularSegurado))
            {
                return new global::LightSwitchApplication.Implementation.CelularSegurado();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Corretores))
            {
                return new global::LightSwitchApplication.Implementation.Corretores();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EnderecoCorretores))
            {
                return new global::LightSwitchApplication.Implementation.EnderecoCorretores();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TelefonesCorretores))
            {
                return new global::LightSwitchApplication.Implementation.TelefonesCorretores();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmailCorretores))
            {
                return new global::LightSwitchApplication.Implementation.EmailCorretores();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CelularCorretores))
            {
                return new global::LightSwitchApplication.Implementation.CelularCorretores();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.BancosCorretores))
            {
                return new global::LightSwitchApplication.Implementation.BancosCorretores();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Ramos))
            {
                return new global::LightSwitchApplication.Implementation.Ramos();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PropostasHeader))
            {
                return new global::LightSwitchApplication.Implementation.PropostasHeader();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Segurados) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Segurados);
            }
            if (typeof(global::LightSwitchApplication.EnderecoSegurado) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EnderecoSegurado);
            }
            if (typeof(global::LightSwitchApplication.EmailSegurado) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmailSegurado);
            }
            if (typeof(global::LightSwitchApplication.TelefonesSegurado) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TelefonesSegurado);
            }
            if (typeof(global::LightSwitchApplication.CelularSegurado) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CelularSegurado);
            }
            if (typeof(global::LightSwitchApplication.Corretores) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Corretores);
            }
            if (typeof(global::LightSwitchApplication.EnderecoCorretores) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EnderecoCorretores);
            }
            if (typeof(global::LightSwitchApplication.TelefonesCorretores) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TelefonesCorretores);
            }
            if (typeof(global::LightSwitchApplication.EmailCorretores) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmailCorretores);
            }
            if (typeof(global::LightSwitchApplication.CelularCorretores) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CelularCorretores);
            }
            if (typeof(global::LightSwitchApplication.BancosCorretores) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.BancosCorretores);
            }
            if (typeof(global::LightSwitchApplication.Ramos) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Ramos);
            }
            if (typeof(global::LightSwitchApplication.PropostasHeader) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PropostasHeader);
            }
            return null;
        }
    }
}
