

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class TelefonesCorretores : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TelefonesCorretores entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TelefonesCorretores()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TelefonesCorretores(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TelefonesCorretores> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TelefonesCorretores.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TelefonesCorretores_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TelefonesCorretores_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Telefone
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Telefone);
            }
            set
            {
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Telefone, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefone_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefone_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefone_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Comercial
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Comercial);
            }
            set
            {
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Comercial, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comercial_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comercial_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comercial_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Recados
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Recados);
            }
            set
            {
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Recados, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recados_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recados_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recados_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Corretores Corretores
        {
            get
            {
                return global::LightSwitchApplication.TelefonesCorretores.DetailsClass.GetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Corretores);
            }
            set
            {
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.SetValue(this, global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Corretores, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Corretores_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Corretores_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Corretores_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TelefonesCorretores,
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass,
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.IImplementation,
                global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass>.Entry
                __TelefonesCorretoresEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass>.Entry(
                    global::LightSwitchApplication.TelefonesCorretores.DetailsClass.__TelefonesCorretores_CreateNew,
                    global::LightSwitchApplication.TelefonesCorretores.DetailsClass.__TelefonesCorretores_Created,
                    global::LightSwitchApplication.TelefonesCorretores.DetailsClass.__TelefonesCorretores_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TelefonesCorretores __TelefonesCorretores_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TelefonesCorretores> es)
            {
                return new global::LightSwitchApplication.TelefonesCorretores(es);
            }
            private static void __TelefonesCorretores_Created(global::LightSwitchApplication.TelefonesCorretores e)
            {
                e.TelefonesCorretores_Created();
            }
            private static bool __TelefonesCorretores_AllowSaveWithErrors(global::LightSwitchApplication.TelefonesCorretores e)
            {
                bool result = false;
                e.TelefonesCorretores_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string> Telefone
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Telefone) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>> Comercial
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Comercial) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>> Recados
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Recados) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::LightSwitchApplication.Corretores> Corretores
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Corretores) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::LightSwitchApplication.Corretores>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Telefone { get; set; }
                new global::System.Nullable<bool> Comercial { get; set; }
                new global::System.Nullable<bool> Recados { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Corretores { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, int>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Entry
                    Telefone = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Entry(
                        "Telefone",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Telefone_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Telefone_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Telefone_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Telefone_GetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Telefone_SetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Telefone_OnValueChanged);
                private static void _Telefone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Telefone, sf);
                }
                private static bool _Telefone_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.Telefone_IsReadOnly(ref result);
                    return result;
                }
                private static void _Telefone_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Telefone_Validate(r);
                }
                private static string _Telefone_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Telefone;
                }
                private static void _Telefone_SetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Telefone = v;
                }
                private static void _Telefone_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.Telefone_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Entry
                    Comercial = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Comercial",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Comercial_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Comercial_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Comercial_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Comercial_GetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Comercial_SetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Comercial_OnValueChanged);
                private static void _Comercial_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Comercial, sf);
                }
                private static bool _Comercial_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.Comercial_IsReadOnly(ref result);
                    return result;
                }
                private static void _Comercial_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Comercial_Validate(r);
                }
                private static global::System.Nullable<bool> _Comercial_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Comercial;
                }
                private static void _Comercial_SetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Comercial = v;
                }
                private static void _Comercial_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.Comercial_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Entry
                    Recados = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Recados",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Recados_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Recados_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Recados_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Recados_GetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Recados_SetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Recados_OnValueChanged);
                private static void _Recados_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Recados, sf);
                }
                private static bool _Recados_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.Recados_IsReadOnly(ref result);
                    return result;
                }
                private static void _Recados_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Recados_Validate(r);
                }
                private static global::System.Nullable<bool> _Recados_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Recados;
                }
                private static void _Recados_SetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Recados = v;
                }
                private static void _Recados_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.Recados_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Entry
                    Corretores = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Entry(
                        "Corretores",
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_Stub,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_ComputeIsReadOnly,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_Validate,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_GetCoreImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_GetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_SetImplementationValue,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_Refresh,
                        global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties._Corretores_OnValueChanged);
                private static void _Corretores_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Data> c, global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, object sf)
                {
                    c(d, ref d._Corretores, sf);
                }
                private static bool _Corretores_ComputeIsReadOnly(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    bool result = false;
                    e.Corretores_IsReadOnly(ref result);
                    return result;
                }
                private static void _Corretores_Validate(global::LightSwitchApplication.TelefonesCorretores e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Corretores_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Corretores_GetCoreImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.ImplementationEntity.Corretores;
                }
                private static global::LightSwitchApplication.Corretores _Corretores_GetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Corretores, global::LightSwitchApplication.Corretores.DetailsClass>(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Corretores, ref d._Corretores);
                }
                private static void _Corretores_SetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d, global::LightSwitchApplication.Corretores v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Corretores, ref d._Corretores, (i, ev) => i.Corretores = ev, v);
                }
                private static void _Corretores_Refresh(global::LightSwitchApplication.TelefonesCorretores.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.TelefonesCorretores.DetailsClass.PropertySetProperties.Corretores, ref d._Corretores);
                }
                private static void _Corretores_OnValueChanged(global::LightSwitchApplication.TelefonesCorretores e)
                {
                    e.Corretores_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Data _Telefone;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Data _Comercial;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<bool>>.Data _Recados;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TelefonesCorretores, global::LightSwitchApplication.TelefonesCorretores.DetailsClass, global::LightSwitchApplication.Corretores>.Data _Corretores;
            
        }
    
        #endregion
    }
    
    #endregion
}
