

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class CelularSegurado : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the CelularSegurado entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CelularSegurado()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CelularSegurado(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CelularSegurado> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CelularSegurado.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CelularSegurado_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CelularSegurado_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.CelularSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Celular
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Celular);
            }
            set
            {
                global::LightSwitchApplication.CelularSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Celular, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Celular_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Celular_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Celular_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Comercial
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Comercial);
            }
            set
            {
                global::LightSwitchApplication.CelularSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Comercial, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comercial_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comercial_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comercial_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Recados
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Recados);
            }
            set
            {
                global::LightSwitchApplication.CelularSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Recados, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recados_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recados_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recados_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Nextel
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Nextel);
            }
            set
            {
                global::LightSwitchApplication.CelularSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Nextel, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nextel_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nextel_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nextel_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.CelularSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Segurados Segurados
        {
            get
            {
                return global::LightSwitchApplication.CelularSegurado.DetailsClass.GetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Segurados);
            }
            set
            {
                global::LightSwitchApplication.CelularSegurado.DetailsClass.SetValue(this, global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Segurados, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Segurados_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Segurados_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Segurados_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CelularSegurado,
                global::LightSwitchApplication.CelularSegurado.DetailsClass,
                global::LightSwitchApplication.CelularSegurado.DetailsClass.IImplementation,
                global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass>.Entry
                __CelularSeguradoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass>.Entry(
                    global::LightSwitchApplication.CelularSegurado.DetailsClass.__CelularSegurado_CreateNew,
                    global::LightSwitchApplication.CelularSegurado.DetailsClass.__CelularSegurado_Created,
                    global::LightSwitchApplication.CelularSegurado.DetailsClass.__CelularSegurado_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CelularSegurado __CelularSegurado_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CelularSegurado> es)
            {
                return new global::LightSwitchApplication.CelularSegurado(es);
            }
            private static void __CelularSegurado_Created(global::LightSwitchApplication.CelularSegurado e)
            {
                e.CelularSegurado_Created();
            }
            private static bool __CelularSegurado_AllowSaveWithErrors(global::LightSwitchApplication.CelularSegurado e)
            {
                bool result = false;
                e.CelularSegurado_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string> Celular
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Celular) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>> Comercial
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Comercial) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>> Recados
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Recados) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>> Nextel
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Nextel) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::LightSwitchApplication.Segurados> Segurados
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Segurados) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::LightSwitchApplication.Segurados>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Celular { get; set; }
                new global::System.Nullable<bool> Comercial { get; set; }
                new global::System.Nullable<bool> Recados { get; set; }
                new global::System.Nullable<bool> Nextel { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Segurados { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, int>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Entry
                    Celular = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Entry(
                        "Celular",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Celular_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Celular_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Celular_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Celular_GetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Celular_SetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Celular_OnValueChanged);
                private static void _Celular_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Celular, sf);
                }
                private static bool _Celular_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Celular_IsReadOnly(ref result);
                    return result;
                }
                private static void _Celular_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Celular_Validate(r);
                }
                private static string _Celular_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Celular;
                }
                private static void _Celular_SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Celular = v;
                }
                private static void _Celular_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Celular_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Entry
                    Comercial = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Comercial",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Comercial_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Comercial_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Comercial_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Comercial_GetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Comercial_SetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Comercial_OnValueChanged);
                private static void _Comercial_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Comercial, sf);
                }
                private static bool _Comercial_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Comercial_IsReadOnly(ref result);
                    return result;
                }
                private static void _Comercial_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Comercial_Validate(r);
                }
                private static global::System.Nullable<bool> _Comercial_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Comercial;
                }
                private static void _Comercial_SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Comercial = v;
                }
                private static void _Comercial_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Comercial_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Entry
                    Recados = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Recados",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Recados_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Recados_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Recados_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Recados_GetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Recados_SetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Recados_OnValueChanged);
                private static void _Recados_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Recados, sf);
                }
                private static bool _Recados_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Recados_IsReadOnly(ref result);
                    return result;
                }
                private static void _Recados_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Recados_Validate(r);
                }
                private static global::System.Nullable<bool> _Recados_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Recados;
                }
                private static void _Recados_SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Recados = v;
                }
                private static void _Recados_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Recados_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Entry
                    Nextel = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Nextel",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Nextel_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Nextel_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Nextel_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Nextel_GetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Nextel_SetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Nextel_OnValueChanged);
                private static void _Nextel_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Nextel, sf);
                }
                private static bool _Nextel_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Nextel_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nextel_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nextel_Validate(r);
                }
                private static global::System.Nullable<bool> _Nextel_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Nextel;
                }
                private static void _Nextel_SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Nextel = v;
                }
                private static void _Nextel_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Nextel_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Entry
                    Segurados = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Entry(
                        "Segurados",
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_Stub,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_ComputeIsReadOnly,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_Validate,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_GetCoreImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_GetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_SetImplementationValue,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_Refresh,
                        global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties._Segurados_OnValueChanged);
                private static void _Segurados_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CelularSegurado.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Data> c, global::LightSwitchApplication.CelularSegurado.DetailsClass d, object sf)
                {
                    c(d, ref d._Segurados, sf);
                }
                private static bool _Segurados_ComputeIsReadOnly(global::LightSwitchApplication.CelularSegurado e)
                {
                    bool result = false;
                    e.Segurados_IsReadOnly(ref result);
                    return result;
                }
                private static void _Segurados_Validate(global::LightSwitchApplication.CelularSegurado e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Segurados_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Segurados_GetCoreImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.ImplementationEntity.Segurados;
                }
                private static global::LightSwitchApplication.Segurados _Segurados_GetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Segurados, global::LightSwitchApplication.Segurados.DetailsClass>(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Segurados, ref d._Segurados);
                }
                private static void _Segurados_SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass d, global::LightSwitchApplication.Segurados v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Segurados, ref d._Segurados, (i, ev) => i.Segurados = ev, v);
                }
                private static void _Segurados_Refresh(global::LightSwitchApplication.CelularSegurado.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CelularSegurado.DetailsClass.PropertySetProperties.Segurados, ref d._Segurados);
                }
                private static void _Segurados_OnValueChanged(global::LightSwitchApplication.CelularSegurado e)
                {
                    e.Segurados_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Data _Celular;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Data _Comercial;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Data _Recados;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<bool>>.Data _Nextel;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CelularSegurado, global::LightSwitchApplication.CelularSegurado.DetailsClass, global::LightSwitchApplication.Segurados>.Data _Segurados;
            
        }
    
        #endregion
    }
    
    #endregion
}
